service:
  name: aws-serverless-backend
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-southeast-2
  stage: ${opt:stage, "dev"}
  tracing:
    lambda: true # AWS X-Ray Tracing
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    TABLE_PREFIX: ${self:service.name}-${self:provider.stage}-
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.TABLE_PREFIX}Item"
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.TABLE_PREFIX}Loan"

package:
  individually: true

functions:
  GetHello:
    handler: src/functions/hello/getHello.lambdaHandler
    events:
      - http:
          method: get
          path: hello
          cors: true
  ListItems:
      handler: src/functions/item/listItems.lambdaHandler
      tracing: Active
      events:
        - http:
            method: get
            path: items
            cors: true          
  GetItemById:
      handler: src/functions/item/getItemById.lambdaHandler
      events:
        - http:
            method: get
            path: items/id/{id}
            cors: true
  GetLoanByStatus:
      handler: src/functions/loan/getLoanByStatus.lambdaHandler
      events:
        - http:
            method: get
            path: loans/status/{status}
            cors: true            
  GetLoanById:
      handler: src/functions/loan/getLoanById.lambdaHandler
      events:
        - http:
            method: get
            path: loans/id/{id}
            cors: true

resources:
  # DynamoDB
  - ${file(./aws-cloudformation/dynamo-tables.yml)}