service:
  name: aws-serverless-backend
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-southeast-2
  stage: ${opt:stage, "dev"}
  tracing:
    lambda: true # AWS X-Ray Tracing
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    TABLE_PREFIX: ${self:service.name}-${self:provider.stage}-
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.TABLE_PREFIX}Item"
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.TABLE_PREFIX}Loan"

package:
  individually: true

functions:
  hello:
    handler: src/functions/hello/hello.lambdaHandler
    events:
      - http:
          method: get
          path: hello
          cors: true
  item:
      handler: src/functions/items/item/item.lambdaHandler
      tracing: Active
      events:
        - http:
            method: get
            path: items
            cors: true          
  item-by-id:
      handler: src/functions/items/item-by-id/item-by-id.lambdaHandler
      events:
        - http:
            method: get
            path: items/id/{id}
            cors: true
  loan-by-status:
      handler: src/functions/loans/loan-by-status/loan-by-status.lambdaHandler
      events:
        - http:
            method: get
            path: loans/status/{status}
            cors: true            
  loan-by-id:
      handler: src/functions/loans/loan-by-id/loan-by-id.lambdaHandler
      events:
        - http:
            method: get
            path: loans/id/{id}
            cors: true

resources:
  # DynamoDB
  - ${file(./aws-cloudformation/dynamo-tables.yml)}