Resources:
  ItemTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.TABLE_PREFIX}Item
      # ****** BillingMode ******
      # If not specified, the default is PROVISIONED.
      # AWS Doco:
      #    PROVISIONED - We recommend using PROVISIONED for predictable workloads. PROVISIONED sets the billing mode to Provisioned Mode.
      #    PAY_PER_REQUEST - We recommend using PAY_PER_REQUEST for unpredictable workloads. PAY_PER_REQUEST sets the billing mode to On-Demand Mode.
      # ***************************
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
  LoanTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.TABLE_PREFIX}Loan
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: by_status
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: status
          AttributeType: S
